### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [edave64/ED-Mahjong#2]
ref: https://f-droid.org/docs/Inclusion_Policy/

reading https://github.com/edave64/ED-Mahjong/blob/884c5aa36f3062ee26f4abc917f6411200f26983/pubspec.yaml#L19 I think flutter 3.7.12 might be good, but fails as  https://github.com/tekartik/sqflite/blob/v2.3.0/sqflite/pubspec.yaml needs 3.19.6

Using 3.19.6 fails:
```
BUILD FAILED in 5m 29s
Running Gradle task 'assembleRelease'...                          330.6s

┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                     │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then │
│ update /home/vagrant/build/org.xcvbnm.ed_mahjong/android/build.gradle:                     │
│ ext.kotlin_version = '<latest-version>'                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────┘
Gradle task assembleRelease failed with exit code 1
```

so, which flutter version?

do add folders and files for Fastlane icon, pics, texts: https://gitlab.com/-/snippets/1895688

**Comment by edave64** [comment]
I've checked on the machine I built the web version with:

```
Flutter 3.19.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 300451adae (4 months ago) • 2024-03-27 21:54:07 -0500
Engine • revision e76c956498
Tools • Dart 3.3.3 • DevTools 2.31.1
```

I'll get to work on the fastlane files

**Comment by edave64** [comment]
Sorry, I misunderstood what you said. I've now rebased the project onto a new empty flutter project, and verified that it builds for android again.

```
Flutter 3.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0850beeb2 (2 weeks ago) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3
```

**Comment by edave64** [comment]
@licaon-kter The fastlane files are added. I don't have a banner, but I think that's ok.

**Comment by licaon-kter** [comment]
Add Flutter as a submodule, that you use during build, or at least take a note in a file of the exact Flutter version used so we can extract this information.

Tag a new release, build from the tagged commit, attach signed APK so we can test for reproducibility (ref: https://f-droid.org/docs/Inclusion_How-To/#reproducible-builds)

/LE: this draft recipe **metadata/org.xcvbnm.ed_mahjong.yml**
```
License: Unknown
SourceCode: https://github.com/edave64/ED-Mahjong
IssueTracker: https://github.com/edave64/ED-Mahjong/issues

AutoName: ed_mahjong

RepoType: git
Repo: https://github.com/edave64/ED-Mahjong

Builds:
  - versionName: 1.0.0
    versionCode: 1
    commit: c74ba1ea9106b53564e1e3e2adb58e13bbebba1b
    output: build/app/outputs/flutter-apk/app-release.apk
    srclibs:
      - flutter@3.22.3
    prebuild:
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter config --no-analytics
      - $$flutter$$/bin/flutter packages pub get
    scandelete:
      - .pub-cache
    build:
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter build apk

AutoUpdateMode: None
UpdateCheckMode: Tags
UpdateCheckData: pubspec.yaml|version:\s.+\+(\d+)|.|version:\s(.+)\+
```
builds fine :smile:
